branches:
  only:
    - main

image: Visual Studio 2022

environment:
  matrix:
  - id: Release.x64
    configuration: Release
    BUILD_DLL: ON
    UNICODE: ON
    arch: amd64
    platform_name: x64
  - id: Release.x86
    configuration: Release
    BUILD_DLL: ON
    UNICODE: ON
    arch: amd64_x86
    platform_name: x86

test: off

install:

build_script:
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch%
  - CALL appveyor.bat

skip_commits:
  message: /.*\[skip appveyor\].*/
