platform:
  - Win64

configuration:
  - Debug

environment:
  matrix:
    - language: cpp
      BUILD_DLL: ON
      UNICODE: ON

test: off

install:

before_build:
  - if %platform%==Win32 set generator=Visual Studio 14
  - if %platform%==Win64 set generator=Visual Studio 14 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64

build_script:
  - CALL appveyor.bat

skip_commits:
  message: /.*\[skip appveyor\].*/
